// const carTypes = {
//   BMW: {
//     "1 Series": [
//       "118d Joy",
//       "118d JOY 5DOOR",
//       "118d Joy First Edition",
//       "118d M Sport",
//       "118d M Sport Shadow 5 Door",
//       "118d Sport",
//       "118d Sport 5Door",
//       "118d Sport Special Edition 5Door",
//       "120",
//       "120 M Sport",
//       "120d M Sport 5Door",
//       "120i Advantage",
//       "120i M Sports",
//       "120i Sports",
//       "M135 xDrive",
//       "M135 xDrive Pro First Edition",
//       "M135i xDrive",
//       "M135i xDrive First Edition",
//       "M135i xDrive Prism",
//     ],
//     "2 Series": [
//       "218 M Sport",
//       "218d Advantage",
//       "218d Luxury",
//       "220 M Sport",
//       "220 M Sport Design",
//       "220d Advantage",
//       "220d Luxury",
//       "220d M Sport Coupe",
//       "220i Advantage",
//       "220i Luxury",
//       "220i M Sport Design",
//       "220i M Sports",
//       "220i Sport",
//       "228 xDrive M Sport",
//       "Advantage",
//       "Joy",
//       "Luxury",
//       "M235 xDrive",
//       "M235i xDrive",
//       "M240i xDrive Coupe",
//       "M240i xDrive First Edition Coupe",
//       "M240i xDrive Online Exclusive Coupe",
//       "Sports Final Edition",
//     ],
//     "3 Series": [
//       "320d",
//       "320d ED Edition",
//       "320d Luxury",
//       "320d M Performence Edition",
//       "320d M Sport",
//       "320d M Sport Pro First Edition",
//       "320d M Sport Shadow",
//       "320d Sport",
//       "320d Touring",
//       "320d Touring Luxury",
//       "320d Touring M Performence",
//       "320d Touring M Sport",
//       "320d Touring M Sport Shadow",
//       "320d xDrive",
//       "320d xDrive Luxury",
//       "320d xDrive M Sport",
//       "320e Luxury",
//       "320e M Sports",
//       "320i",
//       "320i Luxury",
//       "320i M Sport",
//       "320i M Sport Pro Special Edition",
//       "320i M Sport Shadow",
//       "320i Touring",
//       "320i Touring Luxury",
//       "320i Touring M Sport Pro First Edition",
//       "320i Touring M Sports",
//       "328i M Sport",
//       "328i Sport",
//       "328i xDrive",
//       "330e",
//       "330e iPerformance M Sport",
//       "330e Luxury",
//       "330e M Sport",
//       "330i Luxury",
//       "330i M Sport",
//       "330i M Sport Shadow",
//       "330i xDrive Luxury",
//       "330i xDrive M Sport",
//       "GT 320d",
//       "GT 320d Luxury",
//       "GT 320d M Sport Premium",
//       "GT 320d Premium",
//       "GT 320d xDrive",
//       "GT 320d xDrive Premium",
//       "GT 320d xDrive Sport",
//       "M340i",
//       "M340i First Edition",
//       "M340i Individual",
//       "M340i Performance",
//       "M340i Pro",
//       "M340i Pro First edition",
//       "M340i xDrive Touring",
//       "M340i xDrive Touring Performance",
//       "M340i xDrive Touring Pro",
//       "M340i xDrive Touring Pro Special Edition",
//     ],
//     "4 Series": [
//       "420d First Edition Gran Coupe",
//       "420d Luxury Coupe",
//       "420d Luxury GranCoupe",
//       "420d M Sport Coupe",
//       "420d M Sport Performance Gran Coupe",
//       "420d M Sports Grancoupe",
//       "420d xDrive M Sport Coupe",
//       "420d xDrive Sport Coupe",
//       "420d xDrive Sport GranCoupe",
//       "420d xDrive Vision 100 Edition",
//       "420i First Edition GranCoupe",
//       "420i Gran Coupe Special Edition",
//       "420i Luxury GranCoupe",
//       "420i M Sport Convertible",
//       "420i M Sport Coupe",
//       "420i M Sport Gran coupe",
//       "420i M Sport Performance Coupe",
//       "420i M Sport Performance Gran Coupe",
//       "420i M Sport Pro Convertible",
//       "420i M Sport Pro Coupe",
//       "420i M Sport Pro Gran Coupe",
//       "420i M Sports GranCoupe",
//       "428i Convetible vision 100 Edition",
//       "428i M Sport Convertible",
//       "428i M Sport Coupe",
//       "430i First Edition Convertible",
//       "430i First Edition Coupe",
//       "430i Luxury Convertible",
//       "430i M Sport Convertible",
//       "430i M Sport Coupe",
//       "435d xDrive M Sport GranCoupe",
//       "M440i xDrive Convertible",
//       "M440i xDrive Coupe",
//       "M440i xDrive FIrst Edition Coupe",
//       "M440i xDrive Online Exclusive Coupe",
//       "M440i xDrive Pro First Edition Convertible",
//       "M440i xDrive Pro Online Exclusive Convertable",
//     ],
//     "5 Series": [
//       "520d",
//       "520d Luxury",
//       "520d Luxury Plus",
//       "520d Luxury Special Edition",
//       "520d M Aero Dynamic",
//       "520d M Sport",
//       "520d M Sport package",
//       "520d M Sport Package Plus",
//       "520d M Sport Special Edition",
//       "520d xDrive",
//       "520d xDrive Luxury",
//       "520d xDrive Luxury Plus",
//       "520d xDrive M Aero Dynamic",
//       "520d xDrive M Sport Package",
//       "520d xDrive M Sport Package Plus",
//       "520i",
//       "520i Luxury",
//       "520i M Sport",
//       "520i Special Edition",
//       "523d",
//       "523d Luxury",
//       "523d M Sport",
//       "523d xDrive",
//       "523d xDrive Luxury",
//       "523d xDrive M Sport",
//       "528i",
//       "528i Luxury",
//       "528i Luxury Plus",
//       "528i M Aero Dynamic",
//       "528i M Aero dynamic special edition",
//       "528i xDrive",
//       "528i xDrive Aero Dynamic Special Edition",
//       "528i xDrive Luxury",
//       "528i xDrive Luxury Plus",
//       "528i xDrive M Aero Dynamic",
//       "530d Luxury Plus",
//       "530d M Sport Package",
//       "530d M Sport Plus",
//       "530d xDrive M Aero Dynamic",
//       "530e",
//       "530e Luxury",
//       "530e M Sport",
//       "530e M Sport Pro",
//       "530e xDrive M Sport",
//       "530e xDrive M Sport Pro",
//       "530i Luxury",
//       "530i Luxury Plus",
//       "530i M Sport Package",
//       "530i M Sport Package Plus",
//       "530i xDrive",
//       "530i xDrive Luxury",
//       "530i xDrive Luxury Plus",
//       "530i xDrive M Sport",
//       "530i xDrive M Sport Package",
//       "530i xDrive M Sport Package Plus",
//       "530i xDrive M Sport Pro Special Edition",
//       "540i xDrive Luxury Plus",
//       "540i xDrive M Sport",
//       "540i xDrive M Sport Plus",
//       "550e xDrive M Sport Pro",
//       "GT 30d xDrive",
//       "GT ED Edition",
//       "GT xDrive",
//       "GT xDrive Exclusive",
//       "M550d xDrive",
//       "M550d xDrive Aero Dynamic",
//       "M550i xDrive",
//       "P400 AB",
//     ],
//     "6 Series": [
//       "620d Luxury",
//       "620d M Sport",
//       "620d xDrive Luxury",
//       "620d xDrive M Sport",
//       "630d xDrive Luxury",
//       "630d xDrive M Sport",
//       "630i xDrive Luxury",
//       "630i xDrive M Sport",
//       "630i xDrive M Sport Pro Final Edition",
//       "640d M Sport Limited Gran Coupe",
//       "640d xDrive Gran Coupe",
//       "640d xDrive M Sport Gran Coupe",
//       "640d xDrive Sport 20th Gran Coupe",
//       "640i Coupe",
//       "640i Gran Coupe",
//       "640i xDrive Luxury",
//       "640i xDrive M Sport",
//       "650i Convertible",
//     ],
//     "7 Series": [
//       "730d xDrive",
//       "730d xDrive Design Pure Excellence",
//       "730d xDrive individual",
//       "730d xDrive M Sport",
//       "730Ld xDrive",
//       "730Ld xDrive Design Pure Excellence",
//       "730Ld xDrive M Sport",
//       "730Ld xDrive Premium",
//       "740d xDrive",
//       "740d xDrive Design Pure Excellence",
//       "740d xDrive Individual",
//       "740d xDrive M Sport",
//       "740e iPerformance M Sport",
//       "740i Design Pure Excellence",
//       "740i M Sport",
//       "740i sDrive Design Pure Excellence",
//       "740i sDrive Design Pure Excellence Individual",
//       "740i sDrive M Sport",
//       "740i sDrive M Sport Individual",
//       "740i xDrive Classic Silver Edition",
//       "740i xDrive M Sport",
//       "740i xDrive M Sport Limited",
//       "740Ld xDrive",
//       "740Ld xDrive Design Pure Excellence",
//       "740Ld xDrive M Sport",
//       "740Li xDrive",
//       "740Li xDrive Design Pure Excellence",
//       "740Li xDrive M Sport Package",
//       "745e iPerformance Design Pure Excellence",
//       "745e iPerformance M Sport",
//       "745Le iPerformance Design Pure Excellence",
//       "745Le iPerformance M Sport",
//       "750e xDrive Design Pure Excellence",
//       "750e xDrive M Sport",
//       "750Ld xDrive Individual",
//       "750Li xDrive",
//       "750Li xDrive Design Pure Excellence",
//       "750Li xDrive Design Pure Excellence Prestige",
//       "750Li xDrive Individual",
//       "750Li xDrive Luxury",
//       "750Li xDrive Premium",
//       "750Li xDrive Prestige",
//       "750Li xDrive Vision 100 Edition",
//       "M760Li xDrive",
//       "M760Li xDrive V12 Excellence",
//     ],
//     "8 Series": [
//       "840d xDrive M Sport First Edition Gran Coupe",
//       "840d xDrive M Sport Gran Coupe",
//       "840i xDrive M Sport First Edition Gran Coupe",
//       "840i xDrive M Sport Gran Coupe",
//       "M850i xDrive convertible",
//       "M850i xDrive Coupe",
//       "M850i xDrive First Edition Gran Coupe",
//       "M850i xDrive Gran Coupe",
//       "M850i xDrive Gran Coupe Individual Edition",
//       "M850i xDrive Individual Edition Gran Coupe",
//       "M850i xDrive M Performance Gran Coupe",
//     ],
//     "Gran Turismo (GT)": ["Hatchback"],
//     "1M": ["Coupe"],
//     M2: ["Coupe"],
//     M3: ["Sedan", "Touring"],
//     M4: ["Coupe", "Convertible"],
//     M5: ["Sedan", "Touring"],
//     M6: ["Coupe", "Convertible"],
//     M8: ["Coupe", "Convertible"],
//     X1: [
//       "M35i xDrive",
//       "sDrive 18d M Sport",
//       "sDrive 20i M Sport",
//       "sDrive 20i xLine",
//       "xDrive 18d",
//       "xDrive 18d Advantage",
//       "xDrive 18d Joy",
//       "xDrive 18d M Sport",
//       "xDrive 18d Premium",
//       "xDrive 18d xLine",
//       "xDrive 20d",
//       "xDrive 20d Joy",
//       "xDrive 20d M Sport package",
//       "xDrive 20d xLine",
//       "xDrive 20i Advantage",
//       "xDrive 20i M Sport",
//       "xDrive 20i xLine",
//       "xDrive 25i M Sport",
//     ],
//     X2: ["SUV"],
//     X3: ["SUV"],
//     X4: ["SUV"],
//     X5: ["SUV"],
//     X6: ["SUV"],
//     X7: ["SUV"],
//     X3M: ["SUV"],
//     X4M: ["SUV"],
//     X5M: ["SUV"],
//     X6M: ["SUV"],
//     XM: ["SUV"],
//     Z3: ["Roadster"],
//     Z4: ["Roadster"],
//     Z8: ["Roadster"],
//     "M Coupe/Roadster": ["Coupe", "Roadster"],
//     i3: ["Hatchback"],
//     i4: ["Sedan"],
//     i5: ["Sedan"],
//     i7: ["Sedan"],
//     i8: ["Coupe", "Convertible"],
//     iX1: ["SUV"],
//     iX2: ["SUV"],
//     iX3: ["SUV"],
//     iX: ["SUV"],
//     etc: ["Other"],
//   },

//   BYD: {
//     E6: ["MPV"],
//     Dolphin: ["Hatchback"],
//     "Ato 3": ["SUV"],
//     "Sea Lion 7": ["SUV"],
//     Seal: ["Sedan"],
//   },

//   GMC: {
//     Ventura: ["Van"],
//     Savannah: ["Van"],
//     Safari: ["Van"],
//     Sonoma: ["Pickup"],
//     Sierra: ["Pickup"],
//     Acadia: ["SUV"],
//     Yukon: ["SUV"],
//     Jimmy: ["SUV"],
//     Canyon: ["Pickup"],
//     Terrain: ["SUV"],
//     "Hummer EV": ["Pickup", "SUV"],
//     etc: ["Other"],
//   },

//   Nissan: {
//     "180SX": ["Coupe"],
//     "200SX": ["Coupe"],
//     "240SX": ["Coupe"],
//     "280ZX": ["Coupe"],
//     "300ZX": ["Coupe"],
//     "350Z": ["Coupe", "Convertible"],
//     "370Z": ["Coupe", "Convertible"],
//     "GT-R": ["Coupe"],
//     NV: ["Van"],
//     Note: ["Hatchback"],
//     Lafesta: ["MPV"],
//     Rogue: ["SUV"],
//     Leaf: ["Hatchback"],
//     Kicks: ["SUV"],
//     Maxima: ["Sedan"],
//     Moco: ["Hatchback"],
//     Murano: ["SUV"],
//     Versa: ["Sedan"],
//     "Bluebird Sylphy": ["Sedan"],
//     Bluebird: ["Sedan"],
//     Cedric: ["Sedan"],
//     Serena: ["MPV"],
//     Cefiro: ["Sedan"],
//     Sentra: ["Sedan"],
//     Skyline: ["Sedan", "Coupe"],
//     Stagea: ["Wagon"],
//     Cima: ["Sedan"],
//     Silvia: ["Coupe"],
//     Armada: ["SUV"],
//     Altima: ["Sedan"],
//     Xterra: ["SUV"],
//     "X-Trail": ["SUV"],
//     Elgrand: ["MPV"],
//     Wingroad: ["Wagon"],
//     Juke: ["SUV"],
//     Qashqai: ["SUV"],
//     Quest: ["MPV"],
//     Cube: ["Hatchback"],
//     Titan: ["Pickup"],
//     Teana: ["Sedan"],
//     Pao: ["Hatchback"],
//     Pathfinder: ["SUV"],
//     Pulsar: ["Hatchback", "Sedan"],
//     Fuga: ["Sedan"],
//     Prairie: ["MPV"],
//     President: ["Sedan"],
//     Frontier: ["Pickup"],
//     Figaro: ["Convertible"],
//     etc: ["Other"],
//   },

//   Daihatsu: {
//     Materia: ["Hatchback"],
//     Move: ["Hatchback"],
//     Mira: ["Hatchback"],
//     "Mira Gino": ["Hatchback"],
//     Midget: ["Truck"],
//     Esse: ["Hatchback"],
//     Wake: ["Hatchback"],
//     Cast: ["Hatchback"],
//     Copen: ["Convertible"],
//     Tanto: ["Hatchback"],
//     Terios: ["SUV"],
//   },

//   Dodge: {
//     Nitro: ["SUV"],
//     Dakota: ["Pickup"],
//     Durango: ["SUV"],
//     "Ram Bani": ["Van"],
//     "Ram Pickup": ["Pickup"],
//     Magnum: ["Wagon"],
//     Viper: ["Coupe", "Convertible"],
//     Van: ["Van"],
//     Avenger: ["Sedan"],
//     Intrepid: ["Sedan"],
//     Charger: ["Sedan"],
//     Challenger: ["Coupe"],
//     Caravan: ["MPV"],
//     "Grand Caravan": ["MPV"],
//     Caliber: ["Hatchback"],
//     Etc: ["Other"],
//   },
//   Toyota: {
//     Camry: ["Sedan"],
//     Prius: ["Hatchback"],
//     Sienna: ["MPV"],
//     RAV4: ["SUV"],
//     Alphard: ["MPV"],
//     Supra: ["Coupe"],
//     Avalon: ["Sedan"],
//     Crown: ["Sedan"],
//     "4Runner": ["SUV"],
//     "FJ Cruiser": ["SUV"],
//     86: ["Coupe"],
//     Tacoma: ["Pickup"],
//     Tundra: ["Pickup"],
//     Highlander: ["SUV"],
//     "Yaris (Beats)": ["Hatchback"],
//     WiLL: ["Hatchback"],
//     bB: ["Hatchback"],
//     iQ: ["Hatchback"],
//     Noah: ["MPV"],
//     "Land Cruiser": ["SUV"],
//     "Mark II": ["Sedan"],
//     "Mark X": ["Sedan"],
//     Matrix: ["Hatchback"],
//     "Double Vision": ["SUV"],
//     Verso: ["MPV"],
//     Benja: ["Sedan"],
//     Belfire: ["MPV"],
//     Vista: ["Sedan"],
//     Between: ["Sedan"],
//     Sarah: ["Sedan"],
//     Sequoia: ["SUV"],
//     Celica: ["Coupe"],
//     Celcio: ["Sedan"],
//     Soara: ["Coupe"],
//     Solara: ["Convertible", "Coupe"],
//     Sienta: ["MPV"],
//     Aristotle: ["Sedan"],
//     Isis: ["MPV"],
//     Altezza: ["Sedan"],
//     "Extra Cap": ["Pickup"],
//     Estima: ["MPV"],
//     Chaser: ["Sedan"],
//     Karina: ["Sedan"],
//     Corona: ["Sedan"],
//     Corolla: ["Sedan", "Hatchback"],
//     Corsa: ["Hatchback"],
//     Passo: ["Hatchback"],
//     "Fun Cargo": ["MPV"],
//     Forte: ["Pickup"],
//     Premio: ["Sedan"],
//     Privia: ["MPV"],
//     Pickup: ["Pickup"],
//     "Hilux Surf": ["SUV"],
//     Hiace: ["Van"],
//     Harrier: ["SUV"],
//     "MR-2": ["Coupe"],
//     "MR-S": ["Roadster"],
//     Gaia: ["MPV"],
//     Raum: ["MPV"],
//     Lactis: ["Hatchback"],
//     Rumi: ["MPV"],
//     "C-HR": ["SUV"],
//     Mira: ["Hatchback"],
//     Etc: ["Other"],
//   },

//   "Dongfeng Sokon": {
//     C35: ["Van"],
//     "Pencon ix5": ["SUV"],
//     C31: ["Pickup"],
//     C32: ["Pickup"],
//     SX6: ["SUV"],
//   },

//   Lamborghini: {
//     Urus: ["SUV"],
//     Huracan: ["Coupe", "Convertible"],
//     Aventador: ["Coupe", "Convertible"],
//     Revuelto: ["Coupe"],
//     Gallardo: ["Coupe", "Convertible"],
//     Murcielago: ["Coupe", "Convertible"],
//     Diablo: ["Coupe"],
//     Reventon: ["Coupe"],
//     Jalpa: ["Coupe"],
//     Temerario: ["Coupe"],
//     Etc: ["Other"],
//   },

//   "Land Rover": {
//     "Range Rover": ["SUV"],
//     Discovery: ["SUV"],
//     "Discovery Sports": ["SUV"],
//     "Range Rover Evoque": ["SUV"],
//     "Range Rover Sport": ["SUV"],
//     Defender: ["SUV"],
//     "Range Rover Velar": ["SUV"],
//     Freelander: ["SUV"],
//     Etc: ["Other"],
//   },

//   Lexus: {
//     ES: ["Sedan"],
//     NX: ["SUV"],
//     RX: ["SUV"],
//     LS: ["Sedan"],
//     UX: ["SUV"],
//     CT200h: ["Hatchback"],
//     IS: ["Sedan"],
//     LM: ["MPV"],
//     GS: ["Sedan"],
//     LX: ["SUV"],
//     RZ: ["SUV"],
//     SC: ["Convertible", "Coupe"],
//     GX: ["SUV"],
//     RC: ["Coupe"],
//     LC: ["Coupe", "Convertible"],
//     Etc: ["Other"],
//   },

//   "MG Rover": {
//     MG: ["Hatchback"],
//     75: ["Sedan"],
//   },

//   Lotus: {
//     Emira: ["Coupe"],
//     Exige: ["Coupe"],
//     Elettra: ["SUV"],
//     Emeya: ["Sedan"],
//     Evora: ["Coupe"],
//     Alice: ["Roadster"],
//     "2-Eleven": ["Roadster"],
//     Esprit: ["Coupe"],
//     Europa: ["Coupe"],
//     Etc: ["Other"],
//   },

//   "Rolls-Royce": {
//     Ghost: ["Sedan"],
//     Cullinan: ["SUV"],
//     Race: ["Coupe"],
//     Phantom: ["Sedan"],
//     Spectre: ["Coupe"],
//     Dun: ["Sedan"],
//     "Silver Spurs": ["Sedan"],
//     Cornish: ["Convertible"],
//   },

//   Renault: {
//     Laguna: ["Sedan", "Wagon"],
//     Megan: ["Hatchback", "Sedan"],
//     Alpin: ["Coupe"],
//     Clio: ["Hatchback"],
//     Talisman: ["Sedan", "Wagon"],
//     Etc: ["Other"],
//   },

//   Lincoln: {
//     Aviator: ["SUV"],
//     Corsair: ["SUV"],
//     Nautilus: ["SUV"],
//     MKZ: ["Sedan"],
//     Continental: ["Sedan"],
//     MKC: ["SUV"],
//     MKX: ["SUV"],
//     Navigator: ["SUV"],
//     MKS: ["Sedan"],
//     MKT: ["SUV"],
//     "Town Car": ["Sedan"],
//     LS: ["Sedan"],
//   },
//   Maserati: {
//     Levante: ["SUV"],
//     Ghibli: ["Sedan"],
//     Quattroporte: ["Sedan"],
//     Grecale: ["SUV"],
//     "Gran Turismo": ["Coupe"],
//     "Gran Cabrio": ["Convertible"],
//     MC20: ["Coupe", "Convertible"],
//     "Gran Sports": ["Coupe"],
//     Spider: ["Convertible"],
//     Coupe: ["Coupe"],
//     "MC Pura": ["Coupe"],
//     MC12: ["Coupe"],
//     3200: ["Coupe"],
//     Etc: ["Other"],
//   },

//   Maybach: {
//     62: ["Sedan"],
//     57: ["Sedan"],
//     "62s": ["Sedan"],
//     "57s": ["Sedan"],
//     "57 Zeppelin": ["Sedan"],
//     "62 Zeppelin": ["Sedan"],
//     "62s Rendlet": ["Sedan"],
//   },

//   Mazda: {
//     "MX-5 MIATA": ["Convertible"],
//     "Mazda 3": ["Sedan", "Hatchback"],
//     "Mazda 6": ["Sedan", "Wagon"],
//     Viante: ["MPV"],
//     Berisa: ["Sedan"],
//     626: ["Sedan"],
//     "AZ-1": ["Coupe"],
//     "CX-3": ["SUV"],
//     "CX-5": ["SUV"],
//     "CX-7": ["SUV"],
//     "CX-9": ["SUV"],
//     MPV: ["MPV"],
//     "MX-3": ["Coupe"],
//     "MX-6": ["Coupe"],
//     "RX-7": ["Coupe"],
//     "RX-8": ["Coupe"],
//     Demio: ["Hatchback"],
//     "Mazda 5": ["MPV"],
//     Millenia: ["Sedan"],
//     Yunos: ["Coupe"],
//     Protégé: ["Sedan"],
//     "Flare Crossover": ["SUV"],
//     Etc: ["Other"],
//   },

//   McLaren: {
//     GT: ["Coupe"],
//     "570S": ["Coupe"],
//     "650S": ["Coupe", "Convertible"],
//     "750S": ["Coupe", "Convertible"],
//     "720S": ["Coupe", "Convertible"],
//     Artura: ["Coupe", "Convertible"],
//     "570GT": ["Coupe"],
//     "600LT": ["Coupe", "Convertible"],
//     "675LT": ["Coupe", "Convertible"],
//     "765LT": ["Coupe", "Convertible"],
//     "540C": ["Coupe"],
//     "MP4-12C": ["Coupe", "Convertible"],
//     Sena: ["Coupe"],
//   },

//   Mercury: {
//     "Grand Marquis": ["Sedan"],
//     Mystic: ["Sedan"],
//     Villager: ["MPV"],
//     Sable: ["Sedan", "Wagon"],
//     Cougar: ["Coupe"],
//   },

//   Mini: {
//     Cooper: ["Hatchback"],
//     Countryman: ["SUV"],
//     Clubman: ["Wagon"],
//     "Cooper Convertible": ["Convertible"],
//     Coupe: ["Coupe"],
//     Roadster: ["Roadster"],
//     "Ace Man": ["SUV"],
//     Faceman: ["SUV"],
//     "Rover Mini": ["Hatchback"],
//   },

//   Mitsubishi: {
//     "Lancer Evolution": ["Sedan"],
//     Pajero: ["SUV"],
//     Lancer: ["Sedan"],
//     Eclipse: ["Coupe"],
//     Outlander: ["SUV"],
//     "3000GT": ["Coupe"],
//     FTO: ["Coupe"],
//     GTO: ["Coupe"],
//     RVR: ["SUV"],
//     Galang: ["Sedan"],
//     Montero: ["SUV"],
//     Kid: ["Hatchback"],
//     Etc: ["Other"],
//   },

//   Mitsuoka: {
//     Garyu: ["Sedan"],
//     Nuera: ["Sedan"],
//     Laced: ["Sedan"],
//     Rainbow: ["Convertible"],
//     Butte: ["SUV"],
//     Orochi: ["Coupe"],
//     Himiko: ["Convertible"],
//     "Rock Star": ["Convertible"],
//   },

//   "Mercedes-Benz": {
//     "E-Class": ["Sedan", "Estate", "Coupe"],
//     "S-Class": ["Sedan", "Coupe"],
//     "GLC-Class": ["SUV"],
//     "GLE-Class": ["SUV"],
//     "CLS-Class": ["Sedan", "Coupe"],
//     "C-Class": ["Sedan", "Estate", "Coupe"],
//     "GLB-Class": ["SUV"],
//     "A-Class": ["Hatchback", "Sedan"],
//     "G-Class": ["SUV"],
//     "CLA-Class": ["Sedan", "Shooting Brake"],
//     "GLA-Class": ["SUV"],
//     "GLS-Class": ["SUV"],
//     EQS: ["Sedan", "SUV"],
//     "CLE-Class": ["Coupe", "Convertible"],
//     EQE: ["Sedan", "SUV"],
//     EQB: ["SUV"],
//     Sprinter: ["Van"],
//     "B-Class": ["MPV"],
//     "AMG GT": ["Coupe", "Convertible"],
//     EQA: ["SUV"],
//     "GLK-Class": ["SUV"],
//     "SL-Class": ["Convertible"],
//     "SLC-Class": ["Convertible"],
//     "M-Class": ["SUV"],
//     "V-Class": ["MPV"],
//     EQC: ["SUV"],
//     "CL-Class": ["Coupe"],
//     "GL-Class": ["SUV"],
//     "CLK-Class": ["Coupe", "Convertible"],
//     "SEL/SEC": ["Sedan", "Coupe"],
//     "SLS AMG": ["Coupe", "Convertible"],
//     "R-Class": ["MPV"],
//     SLR: ["Coupe", "Convertible"],
//     "190-Class": ["Sedan"],
//     Etc: ["Other"],
//   },

//   Bentley: {
//     Continental: ["Coupe", "Convertible"],
//     "Flying Spur": ["Sedan"],
//     Bentayga: ["SUV"],
//     Mulsan: ["Sedan"],
//     Brooklands: ["Coupe"],
//     Arnage: ["Sedan"],
//     Azur: ["Convertible"],
//     Eight: ["Sedan"],
//   },

//   Volvo: {
//     XC60: ["SUV"],
//     XC90: ["SUV"],
//     XC40: ["SUV"],
//     S90: ["Sedan"],
//     S60: ["Sedan"],
//     V60: ["Wagon"],
//     V90: ["Wagon"],
//     V40: ["Hatchback"],
//     EX30: ["SUV"],
//     S80: ["Sedan"],
//     XC70: ["SUV", "Wagon"],
//     C30: ["Hatchback"],
//     C40: ["SUV"],
//     S40: ["Sedan"],
//     C70: ["Convertible", "Coupe"],
//     EX40: ["SUV"],
//     EX90: ["SUV"],
//     S70: ["Sedan"],
//     V50: ["Wagon"],
//     V70: ["Wagon"],
//     740: ["Sedan"],
//     760: ["Sedan"],
//     850: ["Sedan", "Wagon"],
//     940: ["Sedan", "Wagon"],
//     960: ["Sedan", "Wagon"],
//     Etc: ["Other"],
//   },

//   Bugatti: {
//     "Veyron 16.4": ["Coupe"],
//     EB110: ["Coupe"],
//   },

//   "BAIC Silver Coin": {
//     "Kenbo 600": ["SUV"],
//     "CK Mini Truck": ["Pickup"],
//     "CK Minivan": ["Van"],
//   },

//   Buick: {
//     "Le Sable": ["Sedan"],
//     Legal: ["Sedan"],
//     Century: ["Sedan"],
//     Riviera: ["Coupe"],
//     Terraza: ["MPV"],
//     "Park Avenue": ["Sedan"],
//   },

//   Saab: {
//     "9-3": ["Sedan", "Convertible"],
//     9000: ["Sedan"],
//     900: ["Hatchback", "Convertible"],
//     "9-5": ["Sedan", "Wagon"],
//     Etc: ["Other"],
//   },

//   Science: {
//     tC: ["Coupe"],
//     xB: ["Hatchback"],
//     "FR-S": ["Coupe"],
//     xA: ["Hatchback"],
//     xD: ["Hatchback"],
//   },

//   "Xin Yuan": {
//     "ET Van": ["Van"],
//   },

//   Saturn: {
//     "S series": ["Sedan", "Coupe", "Wagon"],
//     View: ["MPV"],
//     Sky: ["Convertible"],
//     Astra: ["Hatchback"],
//   },

//   Chevrolet: {
//     "Express Van": ["Van"],
//     "Server ban": ["Van"],
//     Corvette: ["Coupe", "Convertible"],
//     Silverado: ["Pickup"],
//     Avalanche: ["Pickup"],
//     Astroband: ["Van"],
//     Tahoe: ["SUV"],
//     "Chevy Van": ["Van"],
//     Tracker: ["SUV"],
//     "S-10": ["Pickup"],
//     Colorado: ["Pickup"],
//     "Pickup Truck": ["Pickup"],
//     Etc: ["Other"],
//     HHR: ["Hatchback"],
//     SSR: ["Pickup", "Convertible"],
//     Lumina: ["Sedan"],
//     Venture: ["MPV"],
//     Volt: ["Sedan"],
//     Blazer: ["SUV"],
//     Equinox: ["SUV"],
//     Camaro: ["Coupe", "Convertible"],
//     "Truck Van": ["Van"],
//   },

//   Smart: {
//     Fortu: ["Hatchback"],
//     Papaw: ["Hatchback"],
//     Roadster: ["Roadster"],
//   },

//   Subaru: {
//     Legacy: ["Sedan", "Wagon"],
//     Outback: ["SUV", "Wagon"],
//     Impreza: ["Sedan", "Hatchback"],
//     Forester: ["SUV"],
//     BRZ: ["Coupe"],
//     R1: ["Hatchback"],
//     SVX: ["Coupe"],
//     Levorg: ["Wagon"],
//   },

//   Suzuki: {
//     Hustler: ["Hatchback"],
//     Jimni: ["SUV"],
//     "Alto Lapin": ["Hatchback"],
//     Alto: ["Hatchback"],
//     Ignis: ["Hatchback", "SUV"],
//     "X-90": ["SUV"],
//     "Grand Vitara": ["SUV"],
//     Sidekick: ["SUV"],
//     Swift: ["Hatchback"],
//     Spacia: ["Hatchback"],
//     "Wagon R": ["Wagon"],
//     Cappuccino: ["Convertible"],
//     Twin: ["Hatchback"],
//     Etc: ["Other"],
//   },
//   "Citroën/DS": {
//     "C4 Picasso": ["MPV"],
//     "C4 Cactus": ["Hatchback", "SUV"],
//     DS3: ["Hatchback"],
//     "C4 Spacetourer": ["MPV"],
//     DS4: ["Hatchback"],
//     DS7: ["SUV"],
//     "C3 Aircross": ["SUV"],
//     "C5 Aircross": ["SUV"],
//     DS5: ["Hatchback"],
//     C2: ["Hatchback"],
//     C3: ["Hatchback"],
//     C5: ["Sedan", "Wagon"],
//     C6: ["Sedan"],
//     XM: ["Sedan"],
//     Xantia: ["Sedan", "Wagon"],
//     Etc: ["Other"],
//   },

//   Audi: {
//     A6: ["Sedan", "Avant"],
//     Q5: ["SUV"],
//     A7: ["Sportback"],
//     Q7: ["SUV"],
//     A4: ["Sedan", "Avant"],
//     A8: ["Sedan"],
//     Q8: ["SUV"],
//     A5: ["Coupe", "Sportback", "Convertible"],
//     A3: ["Sedan", "Hatchback"],
//     Q3: ["SUV"],
//     "e-tron": ["SUV"],
//     SQ5: ["SUV"],
//     Q2: ["SUV"],
//     R8: ["Coupe", "Convertible"],
//     S8: ["Sedan"],
//     "A6 e-tron": ["Sedan"],
//     RS3: ["Sedan", "Hatchback"],
//     RS7: ["Sportback"],
//     S4: ["Sedan", "Avant"],
//     S5: ["Coupe", "Sportback"],
//     S7: ["Sportback"],
//     TT: ["Coupe", "Roadster"],
//     "e-tron GT": ["Sedan"],
//     RS4: ["Sedan", "Avant"],
//     RS5: ["Coupe", "Sportback"],
//     RS6: ["Avant"],
//     S6: ["Sedan", "Avant"],
//     RSQ8: ["SUV"],
//     "Q4 e-tron": ["SUV"],
//     SQ7: ["SUV"],
//     "Q6 e-tron": ["SUV"],
//     A1: ["Hatchback"],
//     "SQ6 e-tron": ["SUV"],
//     S3: ["Sedan", "Hatchback"],
//     TTS: ["Coupe", "Roadster"],
//     "S e-tron GT": ["Sedan"],
//     SQ8: ["SUV"],
//     "Q8 e-tron": ["SUV"],
//     "SQ8 e-tron": ["SUV"],
//     100: ["Sedan"],
//     80: ["Sedan"],
//     90: ["Sedan"],
//     TTRS: ["Coupe", "Roadster"],
//     V8: ["Sedan"],
//     "S6 e-tron": ["Sedan"],
//     "Allroad Quattro": ["Wagon"],
//     Etc: ["Other"],
//   },

//   "Alfa Romeo": {
//     Juliet: ["Hatchback"],
//     "4C": ["Coupe", "Convertible"],
//     Brera: ["Coupe"],
//     Julia: ["Sedan"],
//     147: ["Hatchback"],
//     156: ["Sedan", "Wagon"],
//     159: ["Sedan", "Wagon"],
//     166: ["Sedan"],
//     Mito: ["Hatchback"],
//     Spider: ["Convertible"],
//   },

//   "Aston Martin": {
//     Vantage: ["Coupe", "Convertible"],
//     DBX: ["SUV"],
//     DB11: ["Coupe", "Convertible"],
//     Vanquish: ["Coupe", "Convertible"],
//     DB9: ["Coupe", "Convertible"],
//     DB12: ["Coupe", "Convertible"],
//     Rapid: ["Sedan"],
//     DB7: ["Coupe", "Convertible"],
//     DBS: ["Coupe", "Convertible"],
//     Viraj: ["Coupe", "Convertible"],
//   },

//   Acura: {
//     TSX: ["Sedan"],
//     TL: ["Sedan"],
//     CL: ["Coupe"],
//     ILX: ["Sedan"],
//     MDX: ["SUV"],
//     NSX: ["Coupe"],
//     RDX: ["SUV"],
//     RL: ["Sedan"],
//     RSX: ["Coupe"],
//     TLX: ["Sedan"],
//     Etc: ["Other"],
//   },

//   Opel: {
//     Vectra: ["Sedan", "Wagon"],
//     Vita: ["Hatchback"],
//     Speedster: ["Roadster"],
//     Astra: ["Hatchback", "Sedan", "Wagon"],
//     Corsa: ["Hatchback"],
//     Tigra: ["Coupe", "Convertible"],
//   },

//   Oldsmobile: {
//     Silhouette: ["MPV"],
//     Aurora: ["Sedan"],
//     Cutlass: ["Sedan", "Coupe"],
//     Alero: ["Sedan", "Coupe"],
//     Bravada: ["SUV"],
//   },

//   Ineos: {
//     grenadine: ["SUV"],
//   },

//   Isuzu: {
//     Rodeo: ["SUV", "Pickup"],
//     "V-Cross": ["Pickup"],
//     Trooper: ["SUV"],
//     Etc: ["Other"],
//   },

//   Infinity: {
//     Q50: ["Sedan"],
//     Q30: ["Hatchback"],
//     G: ["Sedan", "Coupe", "Convertible"],
//     QX50: ["SUV"],
//     Q70: ["Sedan"],
//     QX60: ["SUV"],
//     M: ["Sedan"],
//     FX: ["SUV"],
//     QX70: ["SUV"],
//     Q60: ["Coupe", "Convertible"],
//     EX: ["SUV"],
//     QX30: ["SUV"],
//     JX: ["SUV"],
//     QX80: ["SUV"],
//     QX: ["SUV"],
//     J30: ["Sedan"],
//     I: ["Sedan"],
//     Q: ["Sedan"],
//   },

//   Jaguar: {
//     XF: ["Sedan", "Wagon"],
//     XJ: ["Sedan"],
//     XE: ["Sedan"],
//     "F-PACE": ["SUV"],
//     "E-PACE": ["SUV"],
//     "F-TYPE": ["Coupe", "Convertible"],
//     "I-PACE": ["SUV"],
//     "XJ-8": ["Sedan"],
//     "XJ-6": ["Sedan"],
//     Daimler: ["Sedan"],
//     "S-TYPE": ["Sedan"],
//     "X-TYPE": ["Sedan", "Wagon"],
//     XJR: ["Sedan"],
//     XK: ["Coupe", "Convertible"],
//     XKR: ["Coupe", "Convertible"],
//     "E-TYPE": ["Coupe", "Convertible"],
//     "XJ-C": ["Coupe"],
//     XJS: ["Coupe", "Convertible"],
//     XK8: ["Coupe", "Convertible"],
//     Sovereign: ["Sedan"],
//     Etc: ["Other"],
//   },

//   geography: {
//     "SE-A2 van": ["Van"],
//   },
//   Jeep: {
//     Wrangler: ["SUV"],
//     Cherokee: ["SUV"],
//     Renegade: ["SUV"],
//     Compass: ["SUV"],
//     Gladiator: ["Pickup"],
//     Avengers: ["SUV"],
//     Commander: ["SUV"],
//     Patriot: ["SUV"],
//     CJ: ["SUV"],
//   },

//   Cadillac: {
//     Escalade: ["SUV"],
//     CT6: ["Sedan"],
//     CTS: ["Sedan", "Coupe", "Wagon"],
//     XT6: ["SUV"],
//     XT5: ["SUV"],
//     ATS: ["Sedan", "Coupe"],
//     XT4: ["SUV"],
//     CT4: ["Sedan"],
//     CT5: ["Sedan"],
//     Lyrics: ["SUV"],
//     SRX: ["SUV"],
//     "CT5-V": ["Sedan"],
//     DTS: ["Sedan"],
//     "ATS-V": ["Sedan", "Coupe"],
//     STS: ["Sedan"],
//     Deville: ["Sedan"],
//     Concore: ["Sedan"],
//     Fleetwood: ["Sedan"],
//     BLS: ["Sedan"],
//     "CT6-V": ["Sedan"],
//     "CTS-V": ["Sedan", "Coupe"],
//     XLR: ["Convertible"],
//     XTS: ["Sedan"],
//     Sville: ["Sedan"],
//     "El Dorado": ["Coupe"],
//     Etc: ["Other"],
//   },

//   Koenigsegg: {
//     CC: ["Coupe"],
//     Azera: ["Coupe"],
//   },

//   Chrysler: {
//     "300C": ["Sedan"],
//     200: ["Sedan"],
//     "Grand Voyager": ["MPV"],
//     Pacifica: ["MPV"],
//     Sebring: ["Sedan", "Convertible"],
//     Crossfire: ["Coupe", "Convertible"],
//     "300M": ["Sedan"],
//     LHS: ["Sedan"],
//     "PT Cruiser": ["Hatchback", "Convertible"],
//     Neon: ["Sedan"],
//     "New Yorker": ["Sedan"],
//     Lebaron: ["Coupe", "Convertible"],
//     Voyager: ["MPV"],
//     Vision: ["Sedan"],
//     Stratus: ["Sedan", "Coupe"],
//     Cirrus: ["Sedan"],
//     "Eagle Talon": ["Coupe"],
//     Intrepid: ["Sedan"],
//     Caravan: ["MPV"],
//     Concord: ["Sedan"],
//     "Town and Country": ["MPV"],
//     Prowler: ["Convertible"],
//     "Plymouth Laser": ["Coupe"],
//     Etc: ["Other"],
//   },

//   Tesla: {
//     "Model Y": ["SUV"],
//     "Model 3": ["Sedan"],
//     "Model X": ["SUV"],
//     "Model S": ["Sedan"],
//     Cybertruck: ["Pickup"],
//   },

//   Pagani: {
//     Zonda: ["Coupe", "Convertible"],
//     Huira: ["Coupe", "Convertible"],
//   },

//   Ferrari: {
//     Rome: ["Coupe", "Convertible"],
//     296: ["Coupe", "Convertible"],
//     Purosangue: ["SUV"],
//     F8: ["Coupe", "Convertible"],
//     SF90: ["Coupe", "Convertible"],
//     Portofino: ["Convertible"],
//     812: ["Coupe", "Convertible"],
//     488: ["Coupe", "Convertible"],
//     "GTC4 Lusso": ["Shooting Brake"],
//     California: ["Convertible"],
//     458: ["Coupe", "Convertible"],
//     360: ["Coupe", "Convertible"],
//     599: ["Coupe"],
//     "12 Cilindri": ["Coupe", "Convertible"],
//     612: ["Coupe"],
//     "F12 Berlinetta": ["Coupe"],
//     F355: ["Coupe", "Convertible"],
//     F430: ["Coupe", "Convertible"],
//     FF: ["Shooting Brake"],
//     308: ["Coupe", "Convertible"],
//     328: ["Coupe", "Convertible"],
//     348: ["Coupe", "Convertible"],
//     456: ["Coupe"],
//     "512 TR": ["Coupe"],
//     550: ["Coupe"],
//     "575M": ["Coupe"],
//     849: ["Coupe"],
//     F40: ["Coupe"],
//     F50: ["Coupe"],
//     LaFerrari: ["Coupe", "Convertible"],
//     Amalfi: ["Coupe"],
//     "Enzo Ferrari": ["Coupe"],
//   },

//   Ford: {
//     Explorer: ["SUV"],
//     Mustang: ["Coupe", "Convertible"],
//     Ranger: ["Pickup"],
//     Mondeo: ["Sedan", "Wagon"],
//     Bronco: ["SUV"],
//     F150: ["Pickup"],
//     Taurus: ["Sedan"],
//     Expedition: ["SUV"],
//     Kuga: ["SUV"],
//     Transit: ["Van"],
//     Fusion: ["Sedan"],
//     "E-Series": ["Van"],
//     Escape: ["SUV"],
//     Focus: ["Hatchback", "Sedan"],
//     F350: ["Pickup"],
//     F250: ["Pickup"],
//     Econoline: ["Van"],
//     GT: ["Coupe"],
//     "S-MAX": ["MPV"],
//     Thunderbird: ["Coupe", "Convertible"],
//     Windstar: ["MPV"],
//     "Explorer Sports Track": ["Pickup"],
//     "Eco Sports": ["SUV"],
//     Contour: ["Sedan"],
//     "Five Hundred": ["Sedan"],
//     Probe: ["Coupe"],
//     Freestyle: ["SUV"],
//     Flex: ["SUV"],
//     Fiesta: ["Hatchback"],
//     Etc: ["Other"],
//   },

//   Porsche: {
//     Cayenne: ["SUV"],
//     Panamera: ["Sedan"],
//     911: ["Coupe", "Convertible"],
//     Macan: ["SUV"],
//     718: ["Coupe", "Convertible"],
//     Taikan: ["Sedan"],
//     Boxster: ["Convertible"],
//     Cayman: ["Coupe"],
//     928: ["Coupe"],
//     944: ["Coupe"],
//     968: ["Coupe"],
//     "Carrera GT": ["Coupe"],
//     Etc: ["Other"],
//   },

//   Photon: {
//     Tunland: ["Pickup"],
//   },

//   Volkswagen: {
//     Tiguan: ["SUV"],
//     Golf: ["Hatchback"],
//     Arteon: ["Sedan", "Shooting Brake"],
//     Zeta: ["Sedan"],
//     Touareg: ["SUV"],
//     Passat: ["Sedan", "Wagon"],
//     CC: ["Sedan"],
//     "ID.4": ["SUV"],
//     Beetle: ["Hatchback", "Convertible"],
//     Tirok: ["SUV"],
//     Sirocco: ["Coupe"],
//     Atlas: ["SUV"],
//     Peyton: ["Sedan"],
//     Polo: ["Hatchback"],
//     "ID.5": ["SUV"],
//     EOS: ["Convertible"],
//     Multivan: ["MPV"],
//     Etc: ["Other"],
//     Rialta: ["Van"],
//     Microbus: ["Van"],
//     Bento: ["Van"],
//     Purple: ["Van"],
//     Saran: ["MPV"],
//     Up: ["Hatchback"],
//     Corrado: ["Coupe"],
//     Transporter: ["Van"],
//   },

//   Pontiac: {
//     "Grand Prix": ["Sedan"],
//     "Grand Am": ["Sedan"],
//     "Trans Am": ["Coupe"],
//     Transport: ["MPV"],
//     Torrent: ["SUV"],
//     Bonneville: ["Sedan"],
//     Sunfire: ["Coupe", "Convertible"],
//     Solstice: ["Convertible"],
//     Firebird: ["Coupe", "Convertible"],
//     Pierrot: ["Sedan"],
//     G8: ["Sedan"],
//   },

//   Polestar: {
//     "Polestar 2": ["Sedan"],
//     "Polestar 4": ["SUV"],
//   },

//   Peugeot: {
//     3008: ["SUV"],
//     2008: ["SUV"],
//     5008: ["SUV"],
//     508: ["Sedan", "Wagon"],
//     308: ["Hatchback", "Wagon"],
//     208: ["Hatchback"],
//     408: ["Sedan"],
//     207: ["Hatchback", "Sedan"],
//     206: ["Hatchback", "Convertible"],
//     307: ["Hatchback", "Wagon"],
//     RCZ: ["Coupe"],
//     Expert: ["Van"],
//     107: ["Hatchback"],
//     1007: ["Hatchback"],
//     205: ["Hatchback", "Convertible"],
//     306: ["Hatchback", "Sedan"],
//     405: ["Sedan"],
//     406: ["Sedan", "Coupe", "Wagon"],
//     407: ["Sedan", "Wagon"],
//     605: ["Sedan"],
//     607: ["Sedan"],
//     806: ["MPV"],
//     807: ["MPV"],
//     Etc: ["Other"],
//   },

//   Fiat: {
//     500: ["Hatchback", "Convertible"],
//     "500X": ["SUV"],
//     124: ["Convertible"],
//     Ducato: ["Van"],
//     "500L": ["MPV"],
//     Lancia: ["Sedan"],
//     Multipla: ["MPV"],
//     Barchetta: ["Convertible"],
//     Coupe: ["Coupe"],
//     Chroma: ["Wagon"],
//   },

//   Hummer: {
//     H1: ["SUV"],
//     H2: ["SUV"],
//     H3: ["SUV"],
//   },

//   Honda: {
//     Accord: ["Sedan", "Coupe"],
//     "CR-V": ["SUV"],
//     Odyssey: ["MPV"],
//     Pilot: ["SUV"],
//     Civic: ["Sedan", "Hatchback", "Coupe"],
//     Legend: ["Sedan"],
//     "N-BOX": ["Hatchback"],
//     "HR-V": ["SUV"],
//     Ridgeline: ["Pickup"],
//     "Cross Tour": ["Sedan"],
//     "CR-Z": ["Coupe"],
//     S2000: ["Convertible"],
//     "N-ONE": ["Hatchback"],
//     S660: ["Convertible"],
//     "Del Sol": ["Convertible"],
//     "Fit Aria": ["Sedan"],
//     Fit: ["Hatchback"],
//     "That's": ["Hatchback"],
//     Life: ["Hatchback"],
//     Bit: ["Hatchback"],
//     Stepwagon: ["MPV"],
//     Stream: ["MPV"],
//     Element: ["SUV"],
//     Insight: ["Sedan", "Hatchback"],
//     Inspire: ["Sedan"],
//     Integra: ["Coupe", "Sedan"],
//     Crossroads: ["SUV"],
//     Passport: ["SUV"],
//     Prelude: ["Coupe"],
//     Fried: ["MPV"],
//     Etc: ["Other"],
//   },
// };
